import Foundation

struct ListFileGenerator {

    /// Generate a .list file from matched segments.
    /// Merges consecutive segments on the same route into single lines.
    static func generate(from segments: [MatchedSegment], tripName: String? = nil) -> String {
        var lines: [String] = []

        // Header
        let dateStr = Date().formatted(date: .abbreviated, time: .omitted)
        lines.append("# Road trip recorded \(dateStr)")
        if let name = tripName {
            lines.append("# \(name)")
        }
        lines.append("# Generated by TravelMapping iOS App")
        lines.append("")

        // Sort by entry time
        let sorted = segments.sorted { $0.entryTime < $1.entryTime }

        // Merge consecutive segments on the same route
        let merged = mergeConsecutive(sorted)

        // Group by region for organized output
        let grouped = Dictionary(grouping: merged) { $0.region }

        for region in grouped.keys.sorted() {
            guard let regionSegments = grouped[region] else { continue }
            for seg in regionSegments {
                let wp1 = seg.direction == .reverse ? seg.endWaypoint : seg.startWaypoint
                let wp2 = seg.direction == .reverse ? seg.startWaypoint : seg.endWaypoint
                lines.append("\(seg.region) \(seg.routeName) \(wp1) \(wp2)")
            }
        }

        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// Merge consecutive segments that share the same route root
    /// into a single segment spanning from first waypoint to last.
    private static func mergeConsecutive(_ segments: [MatchedSegment]) -> [MatchedSegment] {
        guard !segments.isEmpty else { return [] }

        var result: [MatchedSegment] = []
        var current = segments[0]

        for i in 1..<segments.count {
            let next = segments[i]

            // Can merge if same route and endpoints connect
            if next.root == current.root && canMerge(current: current, next: next) {
                // Extend current to cover the next segment
                let mergedEnd: String
                if current.direction == .forward {
                    mergedEnd = next.direction == .forward ? next.endWaypoint : next.startWaypoint
                } else {
                    mergedEnd = next.direction == .reverse ? next.startWaypoint : next.endWaypoint
                }

                current = MatchedSegment(
                    id: current.id,
                    root: current.root,
                    listName: current.listName,
                    startWaypoint: current.startWaypoint,
                    endWaypoint: mergedEnd,
                    entryTime: current.entryTime,
                    exitTime: next.exitTime,
                    direction: current.direction,
                    confidence: min(current.confidence, next.confidence)
                )
            } else {
                result.append(current)
                current = next
            }
        }
        result.append(current)

        return result
    }

    private static func canMerge(current: MatchedSegment, next: MatchedSegment) -> Bool {
        if current.direction == .forward && next.direction == .forward {
            return current.endWaypoint == next.startWaypoint
        }
        if current.direction == .reverse && next.direction == .reverse {
            return current.startWaypoint == next.endWaypoint
        }
        return false
    }

    // MARK: - Generate from Map Segments (for segment selection export)

    /// Generate .list text from selected MapSegments + route metadata.
    static func generateFromMapSegments(
        _ segments: [TravelMappingAPI.MapSegment],
        routeMetadata: [TravelMappingAPI.RouteMetadata]
    ) -> String {
        var lines: [String] = []
        lines.append("# Selected segments")
        lines.append("# Generated by TravelMapping iOS App")
        lines.append("")

        // Build root → listName lookup
        let rootToName: [String: String] = Dictionary(
            routeMetadata.map { ($0.root, $0.listName) },
            uniquingKeysWith: { first, _ in first }
        )

        // Group segments by root, merge consecutive
        let sorted = segments.sorted { a, b in
            if a.root != b.root { return a.root < b.root }
            return a.id < b.id
        }

        struct SimpleSegment {
            let root: String
            let listName: String
            var startWaypoint: String
            var endWaypoint: String
        }

        var merged: [SimpleSegment] = []
        var current: SimpleSegment?

        for seg in sorted {
            let listName = rootToName[seg.root] ?? seg.root

            if var cur = current, cur.root == seg.root, cur.endWaypoint == seg.startName {
                // Merge: extend current
                cur.endWaypoint = seg.endName
                current = cur
            } else {
                if let cur = current {
                    merged.append(cur)
                }
                current = SimpleSegment(
                    root: seg.root,
                    listName: listName,
                    startWaypoint: seg.startName,
                    endWaypoint: seg.endName
                )
            }
        }
        if let cur = current {
            merged.append(cur)
        }

        // Group by region
        let grouped = Dictionary(grouping: merged) { seg -> String in
            String(seg.listName.split(separator: " ").first ?? "")
        }

        for region in grouped.keys.sorted() {
            guard let segs = grouped[region] else { continue }
            for seg in segs {
                let parts = seg.listName.split(separator: " ", maxSplits: 1)
                let regionCode = parts.count > 0 ? String(parts[0]) : ""
                let routeName = parts.count > 1 ? String(parts[1]) : ""
                lines.append("\(regionCode) \(routeName) \(seg.startWaypoint) \(seg.endWaypoint)")
            }
        }

        lines.append("")
        return lines.joined(separator: "\n")
    }
}
